on: [workflow_dispatch]
jobs:
  test-github-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: test-json-encoding
        with:
          result-encoding: json
          script: return 'a string'
      - name: Get result test-json-encoding
        run: "echo 'result: ${{steps.test-json-encoding.outputs.result}}.'"
      - uses: actions/github-script@v6
        id: test-string-encoding
        with:
          result-encoding: string
          script: return 'a string'
      - name: Get result test-string-encoding
        run: "echo 'result: ${{steps.test-string-encoding.outputs.result}}.'"
      # Note: this seems to use https://github.com/octokit/rest.js which is Javascript. There is also
      # https://github.com/octokit/octokit.js that seems very similar but is Typescrvipt.
      - uses: actions/github-script@v6
        id: set-result
        with:
          # May only be be needed when explicitely returning string, otherwise returns json.
          # If the returned value is a json object and this is set to `string`, the returned value becomes
          # this string:
          #   [object Object]
          #result-encoding: string
          #retries: 3
          # From [Get a repository](https://octokit.github.io/rest.js/v20#repos).
          # Note:
          # - This echos an empty strting below:
          #     github.rest.repos.get(...
          # - This works:
          #     return github.rest.repos.get(...
          # - This echos an empty strting below:
          #     await github.rest.repos.get(...
          # - This works:
          #     return await github.rest.repos.get(...
          # TODO: open an issue about the example in [Retries](https://github.com/actions/github-script#retries).
          # This does not make sense because it gets something but doesn't do anything with it:
          #   github.rest.issues.get({
          # It should be instead:
          #   return github.rest.issues.get({
          #script: |
          #  return github.rest.repos.get({
          #    owner: context.repo.owner,
          #    repo: context.repo.repo,
          #  })
          script: |
            return github.rest.repos.get({
              owner: 'GMZwinge',
              repo: 'test-github-template',
            })
          # This works:
          #script: return "Hello!"
          # This works:
          #script: return context.repo.owner
          # This works:
          #script: return context.repo.repo
      - name: Get result 1
        # WARNING: use single quotes around the string being echoed, otherwise it tries to expand
        # the content of the string.
        run: echo '${{steps.set-result.outputs.result}}'
      # This echos an empty string:
      #- run: "echo 'status: ${{steps.set-result.outputs.result.status}}'"
      # This works:
      - run: "echo 'status: ${{fromJson(steps.set-result.outputs.result).status}}'"
      # This echos an empty string:
      #- run: "echo 'data: ${{steps.set-result.outputs.result.data}}'"
      # This works but only displays `Object`:
      - run: "echo 'data: ${{fromJson(steps.set-result.outputs.result).data}}'"
      # This echos an empty string:
      #- run: "echo 'is_template: ${{steps.set-result.outputs.result.data.is_template}}'"
      # This works:
      - run: "echo 'is_template: ${{fromJson(steps.set-result.outputs.result).data.is_template}}'"
      # This works and display the full name of the template this repository was created from or an empty string:
      - run: "echo 'template_repository: ${{fromJson(steps.set-result.outputs.result).data.template_repository.full_name}}'"
      - uses: actions/github-script@v6
        id: set-result-2
        with:
          script: |
            return github.rest.repos.get({
              owner: 'GMZwinge',
              repo: 'testing-github-template',
            })
      - name: Get result 2
        run: echo '${{steps.set-result-2.outputs.result}}'
      - run: "echo 'status: ${{fromJson(steps.set-result-2.outputs.result).status}}'"
      - run: "echo 'data: ${{fromJson(steps.set-result-2.outputs.result).data}}'"
      #- run: "echo 'is_template: ${{steps.set-result-2.outputs.result.is_template}}'"
      - run: "echo 'is_template: ${{fromJson(steps.set-result-2.outputs.result).data.is_template}}'"
      #- run: "echo 'template_repository: ${{steps.set-result.outputs.result.template_repository}}'"
      # This works but only displays `Object`:
      - run: "echo 'template_repository: ${{fromJson(steps.set-result-2.outputs.result).data.template_repository}}'"
      # This works and display the full name of the template this repository was created from or an empty string:
      - run: "echo 'template_repository: ${{fromJson(steps.set-result-2.outputs.result).data.template_repository.full_name}}'"
