on: [workflow_dispatch]
jobs:
  test-github-action:
    runs-on: ubuntu-latest
    steps:
      # Note: this seems to use https://github.com/octokit/rest.js which is Javascript. There is also
      # https://github.com/octokit/octokit.js that seems very similar but is Typescrvipt.
      - uses: actions/github-script@v6
        id: set-result
        with:
          # May only be be needed when explicitely returning string, otherwise returns json.
          #result-encoding: string
          #retries: 3
          # From [Get a repository](https://octokit.github.io/rest.js/v20#repos).
          # Note:
          # - This echos an empty strting below:
          #     github.rest.repos.get(...
          # - This works:
          #     return github.rest.repos.get(...
          # - This echos an empty strting below:
          #     await github.rest.repos.get(...
          # - This works:
          #     return await github.rest.repos.get(...
          # TODO: open an issue about the example in [Retries](https://github.com/actions/github-script#retries).
          # This does not make sense because it gets something but doesn't do anything with it:
          #   github.rest.issues.get({
          # It should be instead:
          #   return github.rest.issues.get({
          #script: |
          #  return github.rest.repos.get({
          #    owner: context.repo.owner,
          #    repo: context.repo.repo,
          #  })
          script: |
            return github.rest.repos.get({
              owner: 'GMZwinge',
              repo: 'test-github-template',
            })
          # This works:
          #script: return "Hello!"
          # This works:
          #script: return context.repo.owner
          # This works:
          #script: return context.repo.repo
      - name: Get result
        # WARNING: use single quotes around the string being echoed, otherwise it tries to expand
        # the content of the string.
        run: echo '${{steps.set-result.outputs.result}}'
      - run: "echo 'is_template: ${{steps.set-result.outputs.result.is_template}}'"
      - uses: actions/github-script@v6
        id: set-result-2
        with:
          script: |
            return github.rest.repos.get({
              owner: 'GMZwinge',
              repo: 'testing-github-template',
            })
      - run: echo '${{steps.set-result-2.outputs.result}}'
      - run: "echo 'is_template: ${{steps.set-result-2.outputs.result.is_template}}'"
