on: [workflow_dispatch]
jobs:
  test-github-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: set-result
        with:
          # May only be be needed when explicitely returning string, otherwise returns json.
          #result-encoding: string
          retries: 3
          # From [Get a repository](https://octokit.github.io/rest.js/v20#repos).
          # This seems to return undefined:
          script: |
            return github.rest.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
          # This seems to return undefined:
          #script: |
          #  github.rest.repos.get({
          #    owner: 'GMZwinge',
          #    repo: 'demo-dependabot',
          #  })
          # This works:
          #script: return "Hello!"
          # This works:
          #script: return context.repo.owner
          # This works:
          #script: return context.repo.repo
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
